import { SelectOption } from "@/models/types";
import { UserGender, UserRole } from "@/models/types/auth";
import { SchoolLevel } from "@/models/types/onboarding";

export const genderOptions: SelectOption<UserGender>[] = [
    { value: "male", label: "זכר" },
    { value: "female", label: "נקבה" },
    { value: "male", label: "אחר" },
];

export const roleOptions: SelectOption<UserRole>[] = [
    { value: "principal", label: "מנהל/ת" },
    { value: "deputy_principal", label: "סגנ/ית" },
    { value: "teacher", label: "מורה" },
    { value: "teacher", label: "אחר" },
];

export const schoolLevelOptions: SelectOption<SchoolLevel>[] = [
    { value: "elementary", label: "יסודי" },
    { value: "middle", label: "חטיבה" },
    { value: "high", label: "תיכון" },
];

export const citiesOptions: SelectOption<string>[] = [
    { value: "Umm_al_Fahm", label: "אום אל-פחם" },
    { value: "Arad", label: "ערד" },
    { value: "Ariel", label: "אריאל" },
    { value: "Ashkelon", label: "אשקלון" },
    { value: "Ashdod", label: "אשדוד" },
    { value: "Or_Akiva", label: "אור עקיבא" },
    { value: "Or_Yehuda", label: "אור יהודה" },
    { value: "Ofakim", label: "אופקים" },
    { value: "Eilat", label: "אילת" },
    { value: "Elad", label: "אלעד" },
    { value: "Even_Yehuda", label: "אבן יהודה" },
    { value: "Baqa_al_Gharbiyye", label: "באקה אל-גרביה" },
    { value: "BeerSheva", label: "באר שבע" },
    { value: "Bat_Yam", label: "בת ים" },
    { value: "BneiBrak", label: "בני ברק" },
    { value: "Bet_Shemesh", label: "בית שמש" },
    { value: "Beit_Shean", label: "בית שאן" },
    { value: "Beitar_Illit", label: "ביתר עילית" },
    { value: "Givatayim", label: "גבעתיים" },
    { value: "Dimona", label: "דימונה" },
    { value: "Hod_HaSharon", label: "הוד השרון" },
    { value: "Herzliya", label: "הרצליה" },
    { value: "Yavne", label: "יבנה" },
    { value: "Yehud", label: "יהוד" },
    { value: "Yokneam", label: "יקנעם" },
    { value: "Jerusalem", label: "ירושלים" },
    { value: "Zikhron_Yaakov", label: "זכרון יעקב" },
    { value: "Haifa", label: "חיפה" },
    { value: "Hadera", label: "חדרה" },
    { value: "Holon", label: "חולון" },
    { value: "Tiberias", label: "טבריה" },
    { value: "Tayibe", label: "טייבה" },
    { value: "Tira", label: "טירה" },
    { value: "TelAviv", label: "תל אביב" },
    { value: "Tamra", label: "תמרה" },
    { value: "Carmiel", label: "כרמיאל" },
    { value: "Kafr_Qasim", label: "כפר קאסם" },
    { value: "Kfar_Saba", label: "כפר סבא" },
    { value: "Lod", label: "לוד" },
    { value: "Maale_Adumim", label: "מעלה אדומים" },
    { value: "Maalot_Tarshiha", label: "מעלות-תרשיחא" },
    { value: "Migdal_HaEmek", label: "מגדל העמק" },
    { value: "Modi_in", label: "מודיעין" },
    { value: "Modiin_Illit", label: "מודיעין עילית" },
    { value: "Nazareth", label: "נצרת" },
    { value: "Netanya", label: "נתניה" },
    { value: "Netivot", label: "נתיבות" },
    { value: "Nahariya", label: "נהריה" },
    { value: "Nesher", label: "נשר" },
    { value: "Nof_HaGalil", label: "נוף הגליל" },
    { value: "Sakhnin", label: "סח'נין" },
    { value: "Afula", label: "עפולה" },
    { value: "Acre", label: "עכו" },
    { value: "Petah_Tikva", label: "פתח תקווה" },
    { value: "Safed", label: "צפת" },
    { value: "Qalansawe", label: "קלנסווה" },
    { value: "Qatzrin", label: "קצרין" },
    { value: "Kiryat_Ata", label: "קרית אתא" },
    { value: "Kiryat_Ono", label: "קרית אונו" },
    { value: "Kiryat_Bialik", label: "קרית ביאליק" },
    { value: "Kiryat_Gat", label: "קרית גת" },
    { value: "Kiryat_Yam", label: "קרית ים" },
    { value: "Kiryat_Malakhi", label: "קרית מלאכי" },
    { value: "Kiryat_Motzkin", label: "קרית מוצקין" },
    { value: "Kiryat_Shmona", label: "קרית שמונה" },
    { value: "Raanana", label: "רעננה" },
    { value: "Ramla", label: "רמלה" },
    { value: "RamatGan", label: "רמת גן" },
    { value: "RamatHasharon", label: "רמת השרון" },
    { value: "Rehovot", label: "רחובות" },
    { value: "RishonLeZion", label: "ראשון לציון" },
    { value: "Rosh_HaAyin", label: "ראש העין" },
    { value: "Sderot", label: "שדרות" },
    { value: "Shoham", label: "שוהם" },
];


export const schoolsOptions: SelectOption<string>[] = [
    { value: "ORT_Braude_TelAviv", label: "אורט ברודה תל אביב" },
    { value: "ORT_Gutman_Netanya", label: "אורט גוטמן נתניה" },
    { value: "ORT_HaSharon_Kfar_Saba", label: "אורט השרון כפר סבא" },
    { value: "ORT_Kiryat_Bialik", label: "אורט קרית ביאליק" },
    { value: "ORT_Ramat_Ami_Kiryat_Bialik", label: "אורט רמת עמי קרית ביאליק" },
    { value: "ORT_Singalovski_TelAviv", label: "אורט סינגלובסקי תל אביב" },
    { value: "ORT_Amal_Jerusalem", label: "אורט אמל ירושלים" },
    { value: "ORT_Hermelin_Haifa", label: "אורט הרמלין חיפה" },
    { value: "ORT_Shapira_RamatGan", label: "אורט שפירא רמת גן" },
    { value: "ORT_Dvorin_Ashkelon", label: "אורט דבורין אשקלון" },
    { value: "Achva_Elementary_BeerSheva", label: "אחווה יסודי באר שבע" },
    { value: "Achva_Elementary_Jerusalem", label: "אחווה יסודי ירושלים" },
    { value: "Achva_Elementary_Haifa", label: "אחווה יסודי חיפה" },
    { value: "Achva_Elementary_Ashdod", label: "אחווה יסודי אשדוד" },
    { value: "Achva_Elementary_Petah_Tikva", label: "אחווה יסודי פתח תקווה" },
    { value: "Alonim_Elementary_Givatayim", label: "אלונים יסודי גבעתיים" },
    { value: "Alonim_Elementary_RamatGan", label: "אלונים יסודי רמת גן" },
    { value: "Alonim_Elementary_Herzliya", label: "אלונים יסודי הרצליה" },
    { value: "Alonim_Elementary_Netanya", label: "אלונים יסודי נתניה" },
    { value: "Alonim_Elementary_Rehovot", label: "אלונים יסודי רחובות" },
    { value: "Amal_Alef_Jerusalem", label: "אמל א' ירושלים" },
    { value: "Amal_Bet_Haifa", label: "אמל ב' חיפה" },
    { value: "Amal_Gimel_Ashdod", label: "אמל ג' אשדוד" },
    { value: "Amal_Dalet_BeerSheva", label: "אמל ד' באר שבע" },
    { value: "Amal_Heh_TelAviv", label: "אמל ה' תל אביב" },
    { value: "Amal_Vav_Netanya", label: "אמל ו' נתניה" },
    { value: "Amal_Zayin_RishonLeZion", label: "אמל ז' ראשון לציון" },
    { value: "Amal_Het_Petah_Tikva", label: "אמל ח' פתח תקווה" },
    { value: "Amal_Tet_Holon", label: "אמל ט' חולון" },
    { value: "Amal_Yod_BatYam", label: "אמל י' בת ים" },
    { value: "Amirim_Elementary_RamatGan", label: "אמירים יסודי רמת גן" },
    { value: "Amirim_Elementary_Jerusalem", label: "אמירים יסודי ירושלים" },
    { value: "Amirim_Elementary_Haifa", label: "אמירים יסודי חיפה" },
    { value: "Amirim_Elementary_BeerSheva", label: "אמירים יסודי באר שבע" },
    { value: "Amirim_Elementary_Ashkelon", label: "אמירים יסודי אשקלון" },
    { value: "Amit_Elementary_Modi_in", label: "אמית יסודי מודיעין" },
    { value: "Amit_Elementary_Jerusalem", label: "אמית יסודי ירושלים" },
    { value: "Amit_Elementary_TelAviv", label: "אמית יסודי תל אביב" },
    { value: "Amit_Elementary_Haifa", label: "אמית יסודי חיפה" },
    { value: "Amit_Elementary_BeerSheva", label: "אמית יסודי באר שבע" },
    { value: "Ariel_Elementary_Ariel", label: "אריאל יסודי אריאל" },
    { value: "Ariel_Elementary_Jerusalem", label: "אריאל יסודי ירושלים" },
    { value: "Ariel_Elementary_TelAviv", label: "אריאל יסודי תל אביב" },
    { value: "Ariel_Elementary_Haifa", label: "אריאל יסודי חיפה" },
    { value: "Ariel_Elementary_Netanya", label: "אריאל יסודי נתניה" },
    { value: "Eshkol_Elementary_Ashkelon", label: "אשכול יסודי אשקלון" },
    { value: "Eshkol_Elementary_BeerSheva", label: "אשכול יסודי באר שבע" },
    { value: "Eshkol_Elementary_Jerusalem", label: "אשכול יסודי ירושלים" },
    { value: "Eshkol_Elementary_Haifa", label: "אשכול יסודי חיפה" },
    { value: "Eshkol_Elementary_Ashdod", label: "אשכול יסודי אשדוד" },
    { value: "Atzmon_Elementary_Nahariya", label: "אצמון יסודי נהריה" },
    { value: "Atzmon_Elementary_Haifa", label: "אצמון יסודי חיפה" },
    { value: "Atzmon_Elementary_Acre", label: "אצמון יסודי עכו" },
    { value: "Atzmon_Elementary_Kiryat_Shmona", label: "אצמון יסודי קרית שמונה" },
    { value: "Atzmon_Elementary_Safed", label: "אצמון יסודי צפת" },
    { value: "Bialik_Elementary_TelAviv", label: "ביאליק יסודי תל אביב" },
    { value: "Bialik_Elementary_Haifa", label: "ביאליק יסודי חיפה" },
    { value: "Bialik_Elementary_RishonLeZion", label: "ביאליק יסודי ראשון לציון" },
    { value: "Bialik_Elementary_Jerusalem", label: "ביאליק יסודי ירושלים" },
    { value: "Bialik_Elementary_BeerSheva", label: "ביאליק יסודי באר שבע" },
    { value: "Bialik_Elementary_Netanya", label: "ביאליק יסודי נתניה" },
    { value: "Bialik_Elementary_Petah_Tikva", label: "ביאליק יסודי פתח תקווה" },
    { value: "Bialik_Elementary_Ashdod", label: "ביאליק יסודי אשדוד" },
    { value: "Bialik_Elementary_Ashkelon", label: "ביאליק יסודי אשקלון" },
    { value: "Bialik_Elementary_Holon", label: "ביאליק יסודי חולון" },
    { value: "Brenner_Elementary_Givatayim", label: "ברנר יסודי גבעתיים" },
    { value: "Brenner_Elementary_TelAviv", label: "ברנר יסודי תל אביב" },
    { value: "Brenner_Elementary_Haifa", label: "ברנר יסודי חיפה" },
    { value: "Brenner_Elementary_Jerusalem", label: "ברנר יסודי ירושלים" },
    { value: "Brenner_Elementary_RamatGan", label: "ברנר יסודי רמת גן" },
    { value: "Brenner_Middle_School_TelAviv", label: "ברנר חטיבה תל אביב" },
    { value: "Brenner_Middle_School_Jerusalem", label: "ברנר חטיבה ירושלים" },
    { value: "Brenner_Middle_School_Haifa", label: "ברנר חטיבה חיפה" },
    { value: "Brenner_Middle_School_BeerSheva", label: "ברנר חטיבה באר שבע" },
    { value: "Brenner_Middle_School_Ashdod", label: "ברנר חטיבה אשדוד" },
    { value: "Ben_Gurion_Elementary_Petah_Tikva", label: "בן גוריון יסודי פתח תקווה" },
    { value: "Ben_Gurion_Elementary_TelAviv", label: "בן גוריון יסודי תל אביב" },
    { value: "Ben_Gurion_Elementary_Jerusalem", label: "בן גוריון יסודי ירושלים" },
    { value: "Ben_Gurion_Elementary_Haifa", label: "בן גוריון יסודי חיפה" },
    { value: "Ben_Gurion_Elementary_BeerSheva", label: "בן גוריון יסודי באר שבע" },
    { value: "Ben_Gurion_High_School_BeerSheva", label: "בן גוריון תיכון באר שבע" },
    { value: "Ben_Gurion_High_School_Jerusalem", label: "בן גוריון תיכון ירושלים" },
    { value: "Ben_Gurion_High_School_TelAviv", label: "בן גוריון תיכון תל אביב" },
    { value: "Ben_Gurion_High_School_Haifa", label: "בן גוריון תיכון חיפה" },
    { value: "Ben_Gurion_High_School_Ashdod", label: "בן גוריון תיכון אשדוד" },
    { value: "Ben_Zvi_Elementary_Jerusalem", label: "בן צבי יסודי ירושלים" },
    { value: "Ben_Zvi_Elementary_TelAviv", label: "בן צבי יסודי תל אביב" },
    { value: "Ben_Zvi_Elementary_Haifa", label: "בן צבי יסודי חיפה" },
    { value: "Ben_Zvi_Elementary_BeerSheva", label: "בן צבי יסודי באר שבע" },
    { value: "Ben_Zvi_Elementary_Netanya", label: "בן צבי יסודי נתניה" },
    { value: "Geulim_Elementary_Kiryat_Gat", label: "גאולים יסודי קרית גת" },
    { value: "Geulim_Elementary_BeerSheva", label: "גאולים יסודי באר שבע" },
    { value: "Geulim_Elementary_Ashkelon", label: "גאולים יסודי אשקלון" },
    { value: "Geulim_Elementary_Ashdod", label: "גאולים יסודי אשדוד" },
    { value: "Geulim_Elementary_Sderot", label: "גאולים יסודי שדרות" },
    { value: "Gefen_Elementary_Rehovot", label: "גפן יסודי רחובות" },
    { value: "Gefen_Elementary_Jerusalem", label: "גפן יסודי ירושלים" },
    { value: "Gefen_Elementary_TelAviv", label: "גפן יסודי תל אביב" },
    { value: "Gefen_Elementary_Haifa", label: "גפן יסודי חיפה" },
    { value: "Gefen_Elementary_Petah_Tikva", label: "גפן יסודי פתח תקווה" },
    { value: "Darca_High_School_Jerusalem", label: "דרכא תיכון ירושלים" },
    { value: "Darca_High_School_TelAviv", label: "דרכא תיכון תל אביב" },
    { value: "Darca_High_School_Haifa", label: "דרכא תיכון חיפה" },
    { value: "Darca_High_School_BeerSheva", label: "דרכא תיכון באר שבע" },
    { value: "Darca_High_School_Ashdod", label: "דרכא תיכון אשדוד" },
    { value: "Dvora_Baron_Elementary_Petah_Tikva", label: "דבורה ברון יסודי פתח תקווה" },
    { value: "Dvora_Baron_Elementary_TelAviv", label: "דבורה ברון יסודי תל אביב" },
    { value: "Dvora_Baron_Elementary_Jerusalem", label: "דבורה ברון יסודי ירושלים" },
    { value: "Dvora_Baron_Elementary_Haifa", label: "דבורה ברון יסודי חיפה" },
    { value: "Dvora_Baron_Elementary_RamatGan", label: "דבורה ברון יסודי רמת גן" },
    { value: "HaYovel_Elementary_Jerusalem", label: "היובל יסודי ירושלים" },
    { value: "HaYovel_Elementary_TelAviv", label: "היובל יסודי תל אביב" },
    { value: "HaYovel_Elementary_Haifa", label: "היובל יסודי חיפה" },
    { value: "HaYovel_Elementary_BeerSheva", label: "היובל יסודי באר שבע" },
    { value: "HaYovel_Elementary_Ashdod", label: "היובל יסודי אשדוד" },
    { value: "HaZeitim_Elementary_Haifa", label: "הזיתים יסודי חיפה" },
    { value: "HaZeitim_Elementary_Jerusalem", label: "הזיתים יסודי ירושלים" },
    { value: "HaZeitim_Elementary_Nazareth", label: "הזיתים יסודי נצרת" },
    { value: "HaZeitim_Elementary_Acre", label: "הזיתים יסודי עכו" },
    { value: "HaZeitim_Elementary_Tiberias", label: "הזיתים יסודי טבריה" },
    { value: "Hadar_Elementary_Haifa", label: "הדר יסודי חיפה" },
    { value: "Hadar_Elementary_Jerusalem", label: "הדר יסודי ירושלים" },
    { value: "Hadar_Elementary_TelAviv", label: "הדר יסודי תל אביב" },
    { value: "Hadar_Elementary_BeerSheva", label: "הדר יסודי באר שבע" },
    { value: "Hadar_Elementary_Netanya", label: "הדר יסודי נתניה" },
    { value: "Herzl_Elementary_TelAviv", label: "הרצל יסודי תל אביב" },
    { value: "Herzl_Elementary_Netanya", label: "הרצל יסודי נתניה" },
    { value: "Herzl_Elementary_Jerusalem", label: "הרצל יסודי ירושלים" },
    { value: "Herzl_Elementary_Haifa", label: "הרצל יסודי חיפה" },
    { value: "Herzl_Elementary_BeerSheva", label: "הרצל יסודי באר שבע" },
    { value: "Herzl_Elementary_Ashkelon", label: "הרצל יסודי אשקלון" },
    { value: "Herzl_Elementary_Ashdod", label: "הרצל יסודי אשדוד" },
    { value: "Herzl_Elementary_RishonLeZion", label: "הרצל יסודי ראשון לציון" },
    { value: "Herzl_Elementary_Petah_Tikva", label: "הרצל יסודי פתח תקווה" },
    { value: "Herzl_Elementary_Holon", label: "הרצל יסודי חולון" },
    { value: "Herzl_High_School_Givatayim", label: "הרצל תיכון גבעתיים" },
    { value: "Herzl_High_School_TelAviv", label: "הרצל תיכון תל אביב" },
    { value: "Herzl_High_School_Jerusalem", label: "הרצל תיכון ירושלים" },
    { value: "Herzl_High_School_Haifa", label: "הרצל תיכון חיפה" },
    { value: "Herzl_High_School_BeerSheva", label: "הרצל תיכון באר שבע" },
    { value: "HaTikva_Elementary_BneiBrak", label: "התקווה יסודי בני ברק" },
    { value: "HaTikva_Elementary_Jerusalem", label: "התקווה יסודי ירושלים" },
    { value: "HaTikva_Elementary_TelAviv", label: "התקווה יסודי תל אביב" },
    { value: "HaTikva_Elementary_Haifa", label: "התקווה יסודי חיפה" },
    { value: "HaTikva_Elementary_Petah_Tikva", label: "התקווה יסודי פתח תקווה" },
    { value: "Yigal_Alon_High_School_RamatGan", label: "יגאל אלון תיכון רמת גן" },
    { value: "Yigal_Alon_High_School_Jerusalem", label: "יגאל אלון תיכון ירושלים" },
    { value: "Yigal_Alon_High_School_TelAviv", label: "יגאל אלון תיכון תל אביב" },
    { value: "Yigal_Alon_High_School_Haifa", label: "יגאל אלון תיכון חיפה" },
    { value: "Yigal_Alon_High_School_BeerSheva", label: "יגאל אלון תיכון באר שבע" },
    { value: "Yad_Mordechai_Elementary_Ashkelon", label: "יד מרדכי יסודי אשקלון" },
    { value: "Yad_Mordechai_Elementary_BeerSheva", label: "יד מרדכי יסודי באר שבע" },
    { value: "Yad_Mordechai_Elementary_Ashdod", label: "יד מרדכי יסודי אשדוד" },
    { value: "Yad_Mordechai_Elementary_Kiryat_Gat", label: "יד מרדכי יסודי קרית גת" },
    { value: "Yad_Mordechai_Elementary_Sderot", label: "יד מרדכי יסודי שדרות" },
    { value: "Yavneh_Elementary_BneiBrak", label: "יבנה יסודי בני ברק" },
    { value: "Yavneh_Elementary_Jerusalem", label: "יבנה יסודי ירושלים" },
    { value: "Yavneh_Elementary_TelAviv", label: "יבנה יסודי תל אביב" },
    { value: "Yavneh_Elementary_Haifa", label: "יבנה יסודי חיפה" },
    { value: "Yavneh_Elementary_Petah_Tikva", label: "יבנה יסודי פתח תקווה" },
    { value: "Yehuda_HaMaccabi_Elementary_Modi_in", label: "יהודה המכבי יסודי מודיעין" },
    { value: "Yehuda_HaMaccabi_Elementary_Jerusalem", label: "יהודה המכבי יסודי ירושלים" },
    { value: "Yehuda_HaMaccabi_Elementary_TelAviv", label: "יהודה המכבי יסודי תל אביב" },
    { value: "Yehuda_HaMaccabi_Elementary_Haifa", label: "יהודה המכבי יסודי חיפה" },
    { value: "Yehuda_HaMaccabi_Elementary_BeerSheva", label: "יהודה המכבי יסודי באר שבע" },
    { value: "Yeshurun_Elementary_Jerusalem", label: "ישורון יסודי ירושלים" },
    { value: "Yeshurun_Elementary_BneiBrak", label: "ישורון יסודי בני ברק" },
    { value: "Yeshurun_Elementary_TelAviv", label: "ישורון יסודי תל אביב" },
    { value: "Yeshurun_Elementary_Haifa", label: "ישורון יסודי חיפה" },
    { value: "Yeshurun_Elementary_Petah_Tikva", label: "ישורון יסודי פתח תקווה" },
    { value: "Carmel_Zvulun_High_School_Haifa", label: "כרמל צבולון תיכון חיפה" },
    { value: "Carmel_Elementary_Haifa", label: "כרמל יסודי חיפה" },
    { value: "Carmel_Elementary_Jerusalem", label: "כרמל יסודי ירושלים" },
    { value: "Carmel_Elementary_TelAviv", label: "כרמל יסודי תל אביב" },
    { value: "Carmel_Elementary_BeerSheva", label: "כרמל יסודי באר שבע" },
    { value: "Kinneret_Elementary_Tiberias", label: "כנרת יסודי טבריה" },
    { value: "Kinneret_Elementary_Safed", label: "כנרת יסודי צפת" },
    { value: "Kinneret_Elementary_Kiryat_Shmona", label: "כנרת יסודי קרית שמונה" },
    { value: "Kinneret_Elementary_Nahariya", label: "כנרת יסודי נהריה" },
    { value: "Kinneret_Elementary_Acre", label: "כנרת יסודי עכו" },
    { value: "Lea_Goldberg_Elementary_Holon", label: "לאה גולדברג יסודי חולון" },
    { value: "Lea_Goldberg_Elementary_TelAviv", label: "לאה גולדברג יסודי תל אביב" },
    { value: "Lea_Goldberg_Elementary_Jerusalem", label: "לאה גולדברג יסודי ירושלים" },
    { value: "Lea_Goldberg_Elementary_Haifa", label: "לאה גולדברג יסודי חיפה" },
    { value: "Lea_Goldberg_Elementary_BeerSheva", label: "לאה גולדברג יסודי באר שבע" },
    { value: "Makif_Alef_Ashdod", label: "מקיף א' אשדוד" },
    { value: "Makif_Bet_Petah_Tikva", label: "מקיף ב' פתח תקווה" },
    { value: "Makif_Gimel_Haifa", label: "מקיף ג' חיפה" },
    { value: "Makif_Dalet_BeerSheva", label: "מקיף ד' באר שבע" },
    { value: "Makif_Heh_RishonLeZion", label: "מקיף ה' ראשון לציון" },
    { value: "Makif_Vav_Netanya", label: "מקיף ו' נתניה" },
    { value: "Makif_Zayin_Jerusalem", label: "מקיף ז' ירושלים" },
    { value: "Makif_Het_TelAviv", label: "מקיף ח' תל אביב" },
    { value: "Makif_Tet_Holon", label: "מקיף ט' חולון" },
    { value: "Makif_Yod_BatYam", label: "מקיף י' בת ים" },
    { value: "Makif_Yod_Alef_Ashkelon", label: "מקיף יא' אשקלון" },
    { value: "Makif_Yod_Bet_Rehovot", label: "מקיף יב' רחובות" },
    { value: "Makif_Yod_Gimel_Kiryat_Gat", label: "מקיף יג' קרית גת" },
    { value: "Makif_Yod_Dalet_Dimona", label: "מקיף יד' דימונה" },
    { value: "Makif_Tu_Eilat", label: "מקיף טו' אילת" },
    { value: "Mevo_ot_Iron_High_School_Kiryat_Shmona", label: "מבואות עירון תיכון קרית שמונה" },
    { value: "Misgav_Elementary_Carmiel", label: "משגב יסודי כרמיאל" },
    { value: "Misgav_Elementary_Haifa", label: "משגב יסודי חיפה" },
    { value: "Misgav_Elementary_Safed", label: "משגב יסודי צפת" },
    { value: "Misgav_Elementary_Nahariya", label: "משגב יסודי נהריה" },
    { value: "Misgav_Elementary_Acre", label: "משגב יסודי עכו" },
    { value: "Nitzanim_Elementary_RamatHasharon", label: "ניצנים יסודי רמת השרון" },
    { value: "Nitzanim_Elementary_Herzliya", label: "ניצנים יסודי הרצליה" },
    { value: "Nitzanim_Elementary_Kfar_Saba", label: "ניצנים יסודי כפר סבא" },
    { value: "Nitzanim_Elementary_Raanana", label: "ניצנים יסודי רעננה" },
    { value: "Nitzanim_Elementary_Hod_HaSharon", label: "ניצנים יסודי הוד השרון" },
    { value: "Nof_Elementary_Nazareth", label: "נוף יסודי נצרת" },
    { value: "Nof_Elementary_Afula", label: "נוף יסודי עפולה" },
    { value: "Nof_Elementary_Haifa", label: "נוף יסודי חיפה" },
    { value: "Nof_Elementary_Tiberias", label: "נוף יסודי טבריה" },
    { value: "Nof_Elementary_Carmiel", label: "נוף יסודי כרמיאל" },
    { value: "Sapir_Elementary_Herzliya", label: "ספיר יסודי הרצליה" },
    { value: "Sapir_Elementary_TelAviv", label: "ספיר יסודי תל אביב" },
    { value: "Sapir_Elementary_Jerusalem", label: "ספיר יסודי ירושלים" },
    { value: "Sapir_Elementary_Haifa", label: "ספיר יסודי חיפה" },
    { value: "Sapir_Elementary_BeerSheva", label: "ספיר יסודי באר שבע" },
    { value: "Amit_Middle_School_Jerusalem", label: "עמית חטיבה ירושלים" },
    { value: "Amit_Middle_School_Haifa", label: "עמית חטיבה חיפה" },
    { value: "Amit_Middle_School_TelAviv", label: "עמית חטיבה תל אביב" },
    { value: "Amit_Middle_School_BeerSheva", label: "עמית חטיבה באר שבע" },
    { value: "Amit_Middle_School_Ashdod", label: "עמית חטיבה אשדוד" },
    { value: "Peretz_Elementary_TelAviv", label: "פרץ יסודי תל אביב" },
    { value: "Peretz_Elementary_Jerusalem", label: "פרץ יסודי ירושלים" },
    { value: "Peretz_Elementary_Haifa", label: "פרץ יסודי חיפה" },
    { value: "Peretz_Elementary_BeerSheva", label: "פרץ יסודי באר שבע" },
    { value: "Peretz_Elementary_Petah_Tikva", label: "פרץ יסודי פתח תקווה" },
    { value: "Tzemach_Elementary_BeerSheva", label: "צמח יסודי באר שבע" },
    { value: "Tzemach_Elementary_Dimona", label: "צמח יסודי דימונה" },
    { value: "Tzemach_Elementary_Arad", label: "צמח יסודי ערד" },
    { value: "Tzemach_Elementary_Eilat", label: "צמח יסודי אילת" },
    { value: "Tzemach_Elementary_Ofakim", label: "צמח יסודי אופקים" },
    { value: "Ramot_Elementary_Jerusalem", label: "רמות יסודי ירושלים" },
    { value: "Ramot_Elementary_TelAviv", label: "רמות יסודי תל אביב" },
    { value: "Ramot_Elementary_Haifa", label: "רמות יסודי חיפה" },
    { value: "Ramot_Elementary_BeerSheva", label: "רמות יסודי באר שבע" },
    { value: "Ramot_Elementary_Netanya", label: "רמות יסודי נתניה" },
    { value: "Ramot_Remez_Elementary_Haifa", label: "רמות רמז יסודי חיפה" },
    { value: "Rachel_Elementary_Givat_Shmuel", label: "רחל יסודי גבעת שמואל" },
    { value: "Rachel_Elementary_Petah_Tikva", label: "רחל יסודי פתח תקווה" },
    { value: "Rachel_Elementary_TelAviv", label: "רחל יסודי תל אביב" },
    { value: "Rachel_Elementary_Jerusalem", label: "רחל יסודי ירושלים" },
    { value: "Rachel_Elementary_Haifa", label: "רחל יסודי חיפה" },
    { value: "Shazar_Elementary_Jerusalem", label: "שזר יסודי ירושלים" },
    { value: "Shazar_Elementary_TelAviv", label: "שזר יסודי תל אביב" },
    { value: "Shazar_Elementary_Haifa", label: "שזר יסודי חיפה" },
    { value: "Shazar_Elementary_BeerSheva", label: "שזר יסודי באר שבע" },
    { value: "Shazar_Elementary_Ashdod", label: "שזר יסודי אשדוד" },
    { value: "Shilo_Elementary_Ariel", label: "שילה יסודי אריאל" },
    { value: "Shilo_Elementary_Jerusalem", label: "שילה יסודי ירושלים" },
    { value: "Shilo_Elementary_TelAviv", label: "שילה יסודי תל אביב" },
    { value: "Shilo_Elementary_Haifa", label: "שילה יסודי חיפה" },
    { value: "Shilo_Elementary_BeerSheva", label: "שילה יסודי באר שבע" },
    { value: "Sharett_Elementary_Jerusalem", label: "שרת יסודי ירושלים" },
    { value: "Sharett_Elementary_TelAviv", label: "שרת יסודי תל אביב" },
    { value: "Sharett_Elementary_Haifa", label: "שרת יסודי חיפה" },
    { value: "Sharett_Elementary_BeerSheva", label: "שרת יסודי באר שבע" },
    { value: "Sharett_Elementary_Petah_Tikva", label: "שרת יסודי פתח תקווה" },
    { value: "Sheinkin_Elementary_TelAviv", label: "שינקין יסודי תל אביב" },
    { value: "Sheinkin_Elementary_Jerusalem", label: "שינקין יסודי ירושלים" },
    { value: "Sheinkin_Elementary_Haifa", label: "שינקין יסודי חיפה" },
    { value: "Sheinkin_Elementary_RamatGan", label: "שינקין יסודי רמת גן" },
    { value: "Sheinkin_Elementary_Givatayim", label: "שינקין יסודי גבעתיים" },
    { value: "Tchernichovsky_Elementary_TelAviv", label: "טשרניחובסקי יסודי תל אביב" },
    { value: "Tchernichovsky_Elementary_Jerusalem", label: "טשרניחובסקי יסודי ירושלים" },
    { value: "Tchernichovsky_Elementary_Haifa", label: "טשרניחובסקי יסודי חיפה" },
    { value: "Tchernichovsky_Elementary_BeerSheva", label: "טשרניחובסקי יסודי באר שבע" },
    { value: "Tchernichovsky_Elementary_Netanya", label: "טשרניחובסקי יסודי נתניה" },
    { value: "Tchernichovsky_High_School_Holon", label: "טשרניחובסקי תיכון חולון" },
    { value: "Tchernichovsky_High_School_TelAviv", label: "טשרניחובסקי תיכון תל אביב" },
    { value: "Tchernichovsky_High_School_Jerusalem", label: "טשרניחובסקי תיכון ירושלים" },
    { value: "Tchernichovsky_High_School_Haifa", label: "טשרניחובסקי תיכון חיפה" },
    { value: "Tchernichovsky_High_School_BeerSheva", label: "טשרניחובסקי תיכון באר שבע" },
    { value: "Tamar_Elementary_Dimona", label: "תמר יסודי דימונה" },
    { value: "Tamar_Elementary_BeerSheva", label: "תמר יסודי באר שבע" },
    { value: "Tamar_Elementary_Arad", label: "תמר יסודי ערד" },
    { value: "Tamar_Elementary_Eilat", label: "תמר יסודי אילת" },
    { value: "Tamar_Elementary_Ofakim", label: "תמר יסודי אופקים" },
    { value: "Tali_Elementary_Jerusalem", label: "תלי יסודי ירושלים" },
    { value: "Tali_Elementary_TelAviv", label: "תלי יסודי תל אביב" },
    { value: "Tali_Elementary_Haifa", label: "תלי יסודי חיפה" },
    { value: "Tali_Elementary_BeerSheva", label: "תלי יסודי באר שבע" },
    { value: "Tali_Elementary_Netanya", label: "תלי יסודי נתניה" },
    { value: "Taglit_Elementary_Eilat", label: "תגלית יסודי אילת" },
    { value: "Taglit_Elementary_BeerSheva", label: "תגלית יסודי באר שבע" },
    { value: "Taglit_Elementary_Dimona", label: "תגלית יסודי דימונה" },
    { value: "Taglit_Elementary_Arad", label: "תגלית יסודי ערד" },
    { value: "Taglit_Elementary_Ofakim", label: "תגלית יסודי אופקים" },
    { value: "Rogozin_Elementary_TelAviv", label: "רוגוזין יסודי תל אביב" },
    { value: "Rogozin_Elementary_Jerusalem", label: "רוגוזין יסודי ירושלים" },
    { value: "Rogozin_Elementary_Haifa", label: "רוגוזין יסודי חיפה" },
    { value: "Rogozin_Elementary_BeerSheva", label: "רוגוזין יסודי באר שבע" },
    { value: "Rogozin_Elementary_Petah_Tikva", label: "רוגוזין יסודי פתח תקווה" },
    { value: "Nordau_Elementary_TelAviv", label: "נורדאו יסודי תל אביב" },
    { value: "Nordau_Elementary_Jerusalem", label: "נורדאו יסודי ירושלים" },
    { value: "Nordau_Elementary_Haifa", label: "נורדאו יסודי חיפה" },
    { value: "Nordau_Elementary_BeerSheva", label: "נורדאו יסודי באר שבע" },
    { value: "Nordau_Elementary_Netanya", label: "נורדאו יסודי נתניה" },
    { value: "Ahad_Haam_Elementary_TelAviv", label: "אחד העם יסודי תל אביב" },
    { value: "Ahad_Haam_Elementary_Jerusalem", label: "אחד העם יסודי ירושלים" },
    { value: "Ahad_Haam_Elementary_Haifa", label: "אחד העם יסודי חיפה" },
    { value: "Ahad_Haam_Elementary_BeerSheva", label: "אחד העם יסודי באר שבע" },
    { value: "Ahad_Haam_Elementary_RamatGan", label: "אחד העם יסודי רמת גן" },
    { value: "Nes_Ziona_Elementary_Nes_Ziona", label: "נס ציונה יסודי נס ציונה" },
    { value: "Nes_Ziona_Elementary_Rehovot", label: "נס ציונה יסודי רחובות" },
    { value: "Nes_Ziona_Elementary_Yavne", label: "נס ציונה יסודי יבנה" },
    { value: "Nes_Ziona_Elementary_Ashdod", label: "נס ציונה יסודי אשדוד" },
    { value: "Nes_Ziona_Elementary_Ashkelon", label: "נס ציונה יסודי אשקלון" },
    { value: "Rambam_Elementary_Rehovot", label: "רמב\"ם יסודי רחובות" },
    { value: "Rambam_Elementary_Jerusalem", label: "רמב\"ם יסודי ירושלים" },
    { value: "Rambam_Elementary_TelAviv", label: "רמב\"ם יסודי תל אביב" },
    { value: "Rambam_Elementary_Haifa", label: "רמב\"ם יסודי חיפה" },
    { value: "Rambam_Elementary_BeerSheva", label: "רמב\"ם יסודי באר שבע" },
    { value: "Einstein_Elementary_Rehovot", label: "איינשטיין יסודי רחובות" },
    { value: "Einstein_Elementary_Jerusalem", label: "איינשטיין יסודי ירושלים" },
    { value: "Einstein_Elementary_TelAviv", label: "איינשטיין יסודי תל אביב" },
    { value: "Einstein_Elementary_Haifa", label: "איינשטיין יסודי חיפה" },
    { value: "Einstein_Elementary_BeerSheva", label: "איינשטיין יסודי באר שבע" },
    { value: "Weizmann_Elementary_Rehovot", label: "ויצמן יסודי רחובות" },
    { value: "Weizmann_Elementary_Jerusalem", label: "ויצמן יסודי ירושלים" },
    { value: "Weizmann_Elementary_TelAviv", label: "ויצמן יסודי תל אביב" },
    { value: "Weizmann_Elementary_Haifa", label: "ויצמן יסודי חיפה" },
    { value: "Weizmann_Elementary_BeerSheva", label: "ויצמן יסודי באר שבע" },
    { value: "Kiryat_Eliezer_Elementary_Haifa", label: "קרית אליעזר יסודי חיפה" },
    { value: "Kiryat_Yam_Elementary_Kiryat_Yam", label: "קרית ים יסודי קרית ים" },
    { value: "Kiryat_Motzkin_Elementary_Kiryat_Motzkin", label: "קרית מוצקין יסודי קרית מוצקין" },
    { value: "Nesher_Elementary_Nesher", label: "נשר יסודי נשר" },
    { value: "Kiryat_Ata_Elementary_Kiryat_Ata", label: "קרית אתא יסודי קרית אתא" },
    { value: "Nahariya_Elementary_Nahariya", label: "נהריה יסודי נהריה" },
    { value: "Akko_Elementary_Acre", label: "עכו יסודי עכו" },
    { value: "Maalot_Elementary_Maalot_Tarshiha", label: "מעלות יסודי מעלות-תרשיחא" },
    { value: "Kiryat_Shmona_Elementary_Kiryat_Shmona", label: "קרית שמונה יסודי קרית שמונה" },
    { value: "Safed_Elementary_Safed", label: "צפת יסודי צפת" },
    { value: "Tiberias_Elementary_Tiberias", label: "טבריה יסודי טבריה" },
    { value: "Nazareth_Elementary_Nazareth", label: "נצרת יסודי נצרת" },
    { value: "Afula_Elementary_Afula", label: "עפולה יסודי עפולה" },
    { value: "Migdal_HaEmek_Elementary_Migdal_HaEmek", label: "מגדל העמק יסודי מגדל העמק" },
    { value: "Yokneam_Elementary_Yokneam", label: "יקנעם יסודי יקנעם" },
    { value: "Carmiel_Elementary_Carmiel", label: "כרמיאל יסודי כרמיאל" },
    { value: "Nof_HaGalil_Elementary_Nof_HaGalil", label: "נוף הגליל יסודי נוף הגליל" },
    { value: "Sakhnin_Elementary_Sakhnin", label: "סח'נין יסודי סח'נין" },
    { value: "Tamra_Elementary_Tamra", label: "תמרה יסודי תמרה" },
    { value: "Tayibe_Elementary_Tayibe", label: "טייבה יסודי טייבה" },
    { value: "Tira_Elementary_Tira", label: "טירה יסודי טירה" },
    { value: "Kafr_Qasim_Elementary_Kafr_Qasim", label: "כפר קאסם יסודי כפר קאסם" },
    { value: "Qalansawe_Elementary_Qalansawe", label: "קלנסווה יסודי קלנסווה" },
    { value: "Baqa_al_Gharbiyye_Elementary_Baqa_al_Gharbiyye", label: "באקה אל-גרביה יסודי באקה אל-גרביה" },
    { value: "Umm_al_Fahm_Elementary_Umm_al_Fahm", label: "אום אל-פחם יסודי אום אל-פחם" },
    { value: "BeerSheva_Elementary_BeerSheva", label: "באר שבע יסודי באר שבע" },
    { value: "Arad_Elementary_Arad", label: "ערד יסודי ערד" },
    { value: "Dimona_Elementary_Dimona", label: "דימונה יסודי דימונה" },
    { value: "Ofakim_Elementary_Ofakim", label: "אופקים יסודי אופקים" },
    { value: "Netivot_Elementary_Netivot", label: "נתיבות יסודי נתיבות" },
    { value: "Sderot_Elementary_Sderot", label: "שדרות יסודי שדרות" },
    { value: "Eilat_Elementary_Eilat", label: "אילת יסודי אילת" },
    { value: "Mitzpe_Ramon_Elementary_Mitzpe_Ramon", label: "מצפה רמון יסודי מצפה רמון" },
    { value: "Yeroham_Elementary_Yeroham", label: "ירוחם יסודי ירוחם" },
    { value: "Kiryat_Malakhi_Elementary_Kiryat_Malakhi", label: "קרית מלאכי יסודי קרית מלאכי" },
    { value: "Kiryat_Gat_Elementary_Kiryat_Gat", label: "קרית גת יסודי קרית גת" },
    { value: "Lod_Elementary_Lod", label: "לוד יסודי לוד" },
    { value: "Ramla_Elementary_Ramla", label: "רמלה יסודי רמלה" },
    { value: "Bet_Shemesh_Elementary_Bet_Shemesh", label: "בית שמש יסודי בית שמש" },
    { value: "Maale_Adumim_Elementary_Maale_Adumim", label: "מעלה אדומים יסודי מעלה אדומים" },
    { value: "Beitar_Illit_Elementary_Beitar_Illit", label: "ביתר עילית יסודי ביתר עילית" },
    { value: "Modiin_Illit_Elementary_Modiin_Illit", label: "מודיעין עילית יסודי מודיעין עילית" },
    { value: "Or_Yehuda_Elementary_Or_Yehuda", label: "אור יהודה יסודי אור יהודה" },
    { value: "Yehud_Elementary_Yehud", label: "יהוד יסודי יהוד" },
    { value: "Kiryat_Ono_Elementary_Kiryat_Ono", label: "קרית אונו יסודי קרית אונו" },
    { value: "Even_Yehuda_Elementary_Even_Yehuda", label: "אבן יהודה יסודי אבן יהודה" },
    { value: "Or_Akiva_Elementary_Or_Akiva", label: "אור עקיבא יסודי אור עקיבא" },
    { value: "Zikhron_Yaakov_Elementary_Zikhron_Yaakov", label: "זכרון יעקב יסודי זכרון יעקב" },
    { value: "Shoham_Elementary_Shoham", label: "שוהם יסודי שוהם" },
    { value: "Rosh_HaAyin_Elementary_Rosh_HaAyin", label: "ראש העין יסודי ראש העין" },
    { value: "Elad_Elementary_Elad", label: "אלעד יסודי אלעד" },
    { value: "Beit_Shean_Elementary_Beit_Shean", label: "בית שאן יסודי בית שאן" },
    { value: "Qatzrin_Elementary_Qatzrin", label: "קצרין יסודי קצרין" }
];