import { SchoolLevel } from "@/db/schema";
import { SelectOption } from "@/models/types";
import { UserGender, UserRole } from "@/models/types/auth";

export const genderOptions: SelectOption<UserGender>[] = [
    { value: "male", label: "זכר" },
    { value: "female", label: "נקבה" },
    { value: "male", label: "אחר" },
];

export const roleOptions: SelectOption<UserRole>[] = [
    { value: "principal", label: "מנהל/ת" },
    { value: "deputy_principal", label: "סגנ/ית" },
    { value: "teacher", label: "מורה" },
    { value: "teacher", label: "אחר" },
];

export const schoolLevelOptions: SelectOption<SchoolLevel>[] = [
    { value: "Elementary", label: "יסודי" },
    { value: "Middle", label: "חטיבה" },
    { value: "High", label: "תיכון" },
];

export const citiesOptions: SelectOption<string>[] = [
    { value: "Umm_al_Fahm", label: "אום אל-פחם" },
    { value: "Arad", label: "ערד" },
    { value: "Ariel", label: "אריאל" },
    { value: "Ashkelon", label: "אשקלון" },
    { value: "Ashdod", label: "אשדוד" },
    { value: "Or_Akiva", label: "אור עקיבא" },
    { value: "Or_Yehuda", label: "אור יהודה" },
    { value: "Ofakim", label: "אופקים" },
    { value: "Eilat", label: "אילת" },
    { value: "Elad", label: "אלעד" },
    { value: "Even_Yehuda", label: "אבן יהודה" },
    { value: "Baqa_al_Gharbiyye", label: "באקה אל-גרביה" },
    { value: "BeerSheva", label: "באר שבע" },
    { value: "Bat_Yam", label: "בת ים" },
    { value: "BneiBrak", label: "בני ברק" },
    { value: "Bet_Shemesh", label: "בית שמש" },
    { value: "Beit_Shean", label: "בית שאן" },
    { value: "Beitar_Illit", label: "ביתר עילית" },
    { value: "Givatayim", label: "גבעתיים" },
    { value: "Dimona", label: "דימונה" },
    { value: "Hod_HaSharon", label: "הוד השרון" },
    { value: "Herzliya", label: "הרצליה" },
    { value: "Yavne", label: "יבנה" },
    { value: "Yehud", label: "יהוד" },
    { value: "Yokneam", label: "יקנעם" },
    { value: "Jerusalem", label: "ירושלים" },
    { value: "Zikhron_Yaakov", label: "זכרון יעקב" },
    { value: "Haifa", label: "חיפה" },
    { value: "Hadera", label: "חדרה" },
    { value: "Holon", label: "חולון" },
    { value: "Tiberias", label: "טבריה" },
    { value: "Tayibe", label: "טייבה" },
    { value: "Tira", label: "טירה" },
    { value: "TelAviv", label: "תל אביב" },
    { value: "Tamra", label: "תמרה" },
    { value: "Carmiel", label: "כרמיאל" },
    { value: "Kafr_Qasim", label: "כפר קאסם" },
    { value: "Kfar_Saba", label: "כפר סבא" },
    { value: "Lod", label: "לוד" },
    { value: "Maale_Adumim", label: "מעלה אדומים" },
    { value: "Maalot_Tarshiha", label: "מעלות-תרשיחא" },
    { value: "Migdal_HaEmek", label: "מגדל העמק" },
    { value: "Modi_in", label: "מודיעין" },
    { value: "Modiin_Illit", label: "מודיעין עילית" },
    { value: "Nazareth", label: "נצרת" },
    { value: "Netanya", label: "נתניה" },
    { value: "Netivot", label: "נתיבות" },
    { value: "Nahariya", label: "נהריה" },
    { value: "Nesher", label: "נשר" },
    { value: "Nof_HaGalil", label: "נוף הגליל" },
    { value: "Sakhnin", label: "סח'נין" },
    { value: "Afula", label: "עפולה" },
    { value: "Acre", label: "עכו" },
    { value: "Petah_Tikva", label: "פתח תקווה" },
    { value: "Safed", label: "צפת" },
    { value: "Qalansawe", label: "קלנסווה" },
    { value: "Qatzrin", label: "קצרין" },
    { value: "Kiryat_Ata", label: "קרית אתא" },
    { value: "Kiryat_Ono", label: "קרית אונו" },
    { value: "Kiryat_Bialik", label: "קרית ביאליק" },
    { value: "Kiryat_Gat", label: "קרית גת" },
    { value: "Kiryat_Yam", label: "קרית ים" },
    { value: "Kiryat_Malakhi", label: "קרית מלאכי" },
    { value: "Kiryat_Motzkin", label: "קרית מוצקין" },
    { value: "Kiryat_Shmona", label: "קרית שמונה" },
    { value: "Raanana", label: "רעננה" },
    { value: "Ramla", label: "רמלה" },
    { value: "RamatGan", label: "רמת גן" },
    { value: "RamatHasharon", label: "רמת השרון" },
    { value: "Rehovot", label: "רחובות" },
    { value: "RishonLeZion", label: "ראשון לציון" },
    { value: "Rosh_HaAyin", label: "ראש העין" },
    { value: "Sderot", label: "שדרות" },
    { value: "Shoham", label: "שוהם" },
];


export const schoolsOptions: SelectOption<string>[] = [
    { value: "אורט ברודה תל אביב", label: "אורט ברודה תל אביב" },
    { value: "אורט גוטמן נתניה", label: "אורט גוטמן נתניה" },
    { value: "אורט השרון כפר סבא", label: "אורט השרון כפר סבא" },
    { value: "אורט קרית ביאליק", label: "אורט קרית ביאליק" },
    { value: "אורט רמת עמי קרית ביאליק", label: "אורט רמת עמי קרית ביאליק" },
    { value: "אורט סינגלובסקי תל אביב", label: "אורט סינגלובסקי תל אביב" },
    { value: "אורט אמל ירושלים", label: "אורט אמל ירושלים" },
    { value: "אורט הרמלין חיפה", label: "אורט הרמלין חיפה" },
    { value: "אורט שפירא רמת גן", label: "אורט שפירא רמת גן" },
    { value: "אורט דבורין אשקלון", label: "אורט דבורין אשקלון" },
    { value: "אחווה יסודי באר שבע", label: "אחווה יסודי באר שבע" },
    { value: "אחווה יסודי ירושלים", label: "אחווה יסודי ירושלים" },
    { value: "אחווה יסודי חיפה", label: "אחווה יסודי חיפה" },
    { value: "אחווה יסודי אשדוד", label: "אחווה יסודי אשדוד" },
    { value: "אחווה יסודי פתח תקווה", label: "אחווה יסודי פתח תקווה" },
    { value: "אלונים יסודי גבעתיים", label: "אלונים יסודי גבעתיים" },
    { value: "אלונים יסודי רמת גן", label: "אלונים יסודי רמת גן" },
    { value: "אלונים יסודי הרצליה", label: "אלונים יסודי הרצליה" },
    { value: "אלונים יסודי נתניה", label: "אלונים יסודי נתניה" },
    { value: "אלונים יסודי רחובות", label: "אלונים יסודי רחובות" },
    { value: "אמל א' ירושלים", label: "אמל א' ירושלים" },
    { value: "אמל ב' חיפה", label: "אמל ב' חיפה" },
    { value: "אמל ג' אשדוד", label: "אמל ג' אשדוד" },
    { value: "אמל ד' באר שבע", label: "אמל ד' באר שבע" },
    { value: "אמל ה' תל אביב", label: "אמל ה' תל אביב" },
    { value: "אמל ו' נתניה", label: "אמל ו' נתניה" },
    { value: "אמל ז' ראשון לציון", label: "אמל ז' ראשון לציון" },
    { value: "אמל ח' פתח תקווה", label: "אמל ח' פתח תקווה" },
    { value: "אמל ט' חולון", label: "אמל ט' חולון" },
    { value: "אמל י' בת ים", label: "אמל י' בת ים" },
    { value: "אמירים יסודי רמת גן", label: "אמירים יסודי רמת גן" },
    { value: "אמירים יסודי ירושלים", label: "אמירים יסודי ירושלים" },
    { value: "אמירים יסודי חיפה", label: "אמירים יסודי חיפה" },
    { value: "אמירים יסודי באר שבע", label: "אמירים יסודי באר שבע" },
    { value: "אמירים יסודי אשקלון", label: "אמירים יסודי אשקלון" },
    { value: "אמית יסודי מודיעין", label: "אמית יסודי מודיעין" },
    { value: "אמית יסודי ירושלים", label: "אמית יסודי ירושלים" },
    { value: "אמית יסודי תל אביב", label: "אמית יסודי תל אביב" },
    { value: "אמית יסודי חיפה", label: "אמית יסודי חיפה" },
    { value: "אמית יסודי באר שבע", label: "אמית יסודי באר שבע" },
    { value: "אריאל יסודי אריאל", label: "אריאל יסודי אריאל" },
    { value: "אריאל יסודי ירושלים", label: "אריאל יסודי ירושלים" },
    { value: "אריאל יסודי תל אביב", label: "אריאל יסודי תל אביב" },
    { value: "אריאל יסודי חיפה", label: "אריאל יסודי חיפה" },
    { value: "אריאל יסודי נתניה", label: "אריאל יסודי נתניה" },
    { value: "אשכול יסודי אשקלון", label: "אשכול יסודי אשקלון" },
    { value: "אשכול יסודי באר שבע", label: "אשכול יסודי באר שבע" },
    { value: "אשכול יסודי ירושלים", label: "אשכול יסודי ירושלים" },
    { value: "אשכול יסודי חיפה", label: "אשכול יסודי חיפה" },
    { value: "אשכול יסודי אשדוד", label: "אשכול יסודי אשדוד" },
    { value: "אצמון יסודי נהריה", label: "אצמון יסודי נהריה" },
    { value: "אצמון יסודי חיפה", label: "אצמון יסודי חיפה" },
    { value: "אצמון יסודי עכו", label: "אצמון יסודי עכו" },
    { value: "אצמון יסודי קרית שמונה", label: "אצמון יסודי קרית שמונה" },
    { value: "אצמון יסודי צפת", label: "אצמון יסודי צפת" },
    { value: "ביאליק יסודי תל אביב", label: "ביאליק יסודי תל אביב" },
    { value: "ביאליק יסודי חיפה", label: "ביאליק יסודי חיפה" },
    { value: "ביאליק יסודי ראשון לציון", label: "ביאליק יסודי ראשון לציון" },
    { value: "ביאליק יסודי ירושלים", label: "ביאליק יסודי ירושלים" },
    { value: "ביאליק יסודי באר שבע", label: "ביאליק יסודי באר שבע" },
    { value: "ביאליק יסודי נתניה", label: "ביאליק יסודי נתניה" },
    { value: "ביאליק יסודי פתח תקווה", label: "ביאליק יסודי פתח תקווה" },
    { value: "ביאליק יסודי אשדוד", label: "ביאליק יסודי אשדוד" },
    { value: "ביאליק יסודי אשקלון", label: "ביאליק יסודי אשקלון" },
    { value: "ביאליק יסודי חולון", label: "ביאליק יסודי חולון" },
    { value: "ברנר יסודי גבעתיים", label: "ברנר יסודי גבעתיים" },
    { value: "ברנר יסודי תל אביב", label: "ברנר יסודי תל אביב" },
    { value: "ברנר יסודי חיפה", label: "ברנר יסודי חיפה" },
    { value: "ברנר יסודי ירושלים", label: "ברנר יסודי ירושלים" },
    { value: "ברנר יסודי רמת גן", label: "ברנר יסודי רמת גן" },
    { value: "ברנר חטיבה תל אביב", label: "ברנר חטיבה תל אביב" },
    { value: "ברנר חטיבה ירושלים", label: "ברנר חטיבה ירושלים" },
    { value: "ברנר חטיבה חיפה", label: "ברנר חטיבה חיפה" },
    { value: "ברנר חטיבה באר שבע", label: "ברנר חטיבה באר שבע" },
    { value: "ברנר חטיבה אשדוד", label: "ברנר חטיבה אשדוד" },
    { value: "בן גוריון יסודי פתח תקווה", label: "בן גוריון יסודי פתח תקווה" },
    { value: "בן גוריון יסודי תל אביב", label: "בן גוריון יסודי תל אביב" },
    { value: "בן גוריון יסודי ירושלים", label: "בן גוריון יסודי ירושלים" },
    { value: "בן גוריון יסודי חיפה", label: "בן גוריון יסודי חיפה" },
    { value: "בן גוריון יסודי באר שבע", label: "בן גוריון יסודי באר שבע" },
    { value: "בן גוריון תיכון באר שבע", label: "בן גוריון תיכון באר שבע" },
    { value: "בן גוריון תיכון ירושלים", label: "בן גוריון תיכון ירושלים" },
    { value: "בן גוריון תיכון תל אביב", label: "בן גוריון תיכון תל אביב" },
    { value: "בן גוריון תיכון חיפה", label: "בן גוריון תיכון חיפה" },
    { value: "בן גוריון תיכון אשדוד", label: "בן גוריון תיכון אשדוד" },
    { value: "בן צבי יסודי ירושלים", label: "בן צבי יסודי ירושלים" },
    { value: "בן צבי יסודי תל אביב", label: "בן צבי יסודי תל אביב" },
    { value: "בן צבי יסודי חיפה", label: "בן צבי יסודי חיפה" },
    { value: "בן צבי יסודי באר שבע", label: "בן צבי יסודי באר שבע" },
    { value: "בן צבי יסודי נתניה", label: "בן צבי יסודי נתניה" },
    { value: "גאולים יסודי קרית גת", label: "גאולים יסודי קרית גת" },
    { value: "גאולים יסודי באר שבע", label: "גאולים יסודי באר שבע" },
    { value: "גאולים יסודי אשקלון", label: "גאולים יסודי אשקלון" },
    { value: "גאולים יסודי אשדוד", label: "גאולים יסודי אשדוד" },
    { value: "גאולים יסודי שדרות", label: "גאולים יסודי שדרות" },
    { value: "גפן יסודי רחובות", label: "גפן יסודי רחובות" },
    { value: "גפן יסודי ירושלים", label: "גפן יסודי ירושלים" },
    { value: "גפן יסודי תל אביב", label: "גפן יסודי תל אביב" },
    { value: "גפן יסודי חיפה", label: "גפן יסודי חיפה" },
    { value: "גפן יסודי פתח תקווה", label: "גפן יסודי פתח תקווה" },
    { value: "דרכא תיכון ירושלים", label: "דרכא תיכון ירושלים" },
    { value: "דרכא תיכון תל אביב", label: "דרכא תיכון תל אביב" },
    { value: "דרכא תיכון חיפה", label: "דרכא תיכון חיפה" },
    { value: "דרכא תיכון באר שבע", label: "דרכא תיכון באר שבע" },
    { value: "דרכא תיכון אשדוד", label: "דרכא תיכון אשדוד" },
    { value: "דבורה ברון יסודי פתח תקווה", label: "דבורה ברון יסודי פתח תקווה" },
    { value: "דבורה ברון יסודי תל אביב", label: "דבורה ברון יסודי תל אביב" },
    { value: "דבורה ברון יסודי ירושלים", label: "דבורה ברון יסודי ירושלים" },
    { value: "דבורה ברון יסודי חיפה", label: "דבורה ברון יסודי חיפה" },
    { value: "דבורה ברון יסודי רמת גן", label: "דבורה ברון יסודי רמת גן" },
    { value: "היובל יסודי ירושלים", label: "היובל יסודי ירושלים" },
    { value: "היובל יסודי תל אביב", label: "היובל יסודי תל אביב" },
    { value: "היובל יסודי חיפה", label: "היובל יסודי חיפה" },
    { value: "היובל יסודי באר שבע", label: "היובל יסודי באר שבע" },
    { value: "היובל יסודי אשדוד", label: "היובל יסודי אשדוד" },
    { value: "הזיתים יסודי חיפה", label: "הזיתים יסודי חיפה" },
    { value: "הזיתים יסודי ירושלים", label: "הזיתים יסודי ירושלים" },
    { value: "הזיתים יסודי נצרת", label: "הזיתים יסודי נצרת" },
    { value: "הזיתים יסודי עכו", label: "הזיתים יסודי עכו" },
    { value: "הזיתים יסודי טבריה", label: "הזיתים יסודי טבריה" },
    { value: "הדר יסודי חיפה", label: "הדר יסודי חיפה" },
    { value: "הדר יסודי ירושלים", label: "הדר יסודי ירושלים" },
    { value: "הדר יסודי תל אביב", label: "הדר יסודי תל אביב" },
    { value: "הדר יסודי באר שבע", label: "הדר יסודי באר שבע" },
    { value: "הדר יסודי נתניה", label: "הדר יסודי נתניה" },
    { value: "הרצל יסודי תל אביב", label: "הרצל יסודי תל אביב" },
    { value: "הרצל יסודי נתניה", label: "הרצל יסודי נתניה" },
    { value: "הרצל יסודי ירושלים", label: "הרצל יסודי ירושלים" },
    { value: "הרצל יסודי חיפה", label: "הרצל יסודי חיפה" },
    { value: "הרצל יסודי באר שבע", label: "הרצל יסודי באר שבע" },
    { value: "הרצל יסודי אשקלון", label: "הרצל יסודי אשקלון" },
    { value: "הרצל יסודי אשדוד", label: "הרצל יסודי אשדוד" },
    { value: "הרצל יסודי ראשון לציון", label: "הרצל יסודי ראשון לציון" },
    { value: "הרצל יסודי פתח תקווה", label: "הרצל יסודי פתח תקווה" },
    { value: "הרצל יסודי חולון", label: "הרצל יסודי חולון" },
    { value: "הרצל תיכון גבעתיים", label: "הרצל תיכון גבעתיים" },
    { value: "הרצל תיכון תל אביב", label: "הרצל תיכון תל אביב" },
    { value: "הרצל תיכון ירושלים", label: "הרצל תיכון ירושלים" },
    { value: "הרצל תיכון חיפה", label: "הרצל תיכון חיפה" },
    { value: "הרצל תיכון באר שבע", label: "הרצל תיכון באר שבע" },
    { value: "התקווה יסודי בני ברק", label: "התקווה יסודי בני ברק" },
    { value: "התקווה יסודי ירושלים", label: "התקווה יסודי ירושלים" },
    { value: "התקווה יסודי תל אביב", label: "התקווה יסודי תל אביב" },
    { value: "התקווה יסודי חיפה", label: "התקווה יסודי חיפה" },
    { value: "התקווה יסודי פתח תקווה", label: "התקווה יסודי פתח תקווה" },
    { value: "יגאל אלון תיכון רמת גן", label: "יגאל אלון תיכון רמת גן" },
    { value: "יגאל אלון תיכון ירושלים", label: "יגאל אלון תיכון ירושלים" },
    { value: "יגאל אלון תיכון תל אביב", label: "יגאל אלון תיכון תל אביב" },
    { value: "יגאל אלון תיכון חיפה", label: "יגאל אלון תיכון חיפה" },
    { value: "יגאל אלון תיכון באר שבע", label: "יגאל אלון תיכון באר שבע" },
    { value: "יד מרדכי יסודי אשקלון", label: "יד מרדכי יסודי אשקלון" },
    { value: "יד מרדכי יסודי באר שבע", label: "יד מרדכי יסודי באר שבע" },
    { value: "יד מרדכי יסודי אשדוד", label: "יד מרדכי יסודי אשדוד" },
    { value: "יד מרדכי יסודי קרית גת", label: "יד מרדכי יסודי קרית גת" },
    { value: "יד מרדכי יסודי שדרות", label: "יד מרדכי יסודי שדרות" },
    { value: "יבנה יסודי בני ברק", label: "יבנה יסודי בני ברק" },
    { value: "יבנה יסודי ירושלים", label: "יבנה יסודי ירושלים" },
    { value: "יבנה יסודי תל אביב", label: "יבנה יסודי תל אביב" },
    { value: "יבנה יסודי חיפה", label: "יבנה יסודי חיפה" },
    { value: "יבנה יסודי פתח תקווה", label: "יבנה יסודי פתח תקווה" },
    { value: "יהודה המכבי יסודי מודיעין", label: "יהודה המכבי יסודי מודיעין" },
    { value: "יהודה המכבי יסודי ירושלים", label: "יהודה המכבי יסודי ירושלים" },
    { value: "יהודה המכבי יסודי תל אביב", label: "יהודה המכבי יסודי תל אביב" },
    { value: "יהודה המכבי יסודי חיפה", label: "יהודה המכבי יסודי חיפה" },
    { value: "יהודה המכבי יסודי באר שבע", label: "יהודה המכבי יסודי באר שבע" },
    { value: "ישורון יסודי ירושלים", label: "ישורון יסודי ירושלים" },
    { value: "ישורון יסודי בני ברק", label: "ישורון יסודי בני ברק" },
    { value: "ישורון יסודי תל אביב", label: "ישורון יסודי תל אביב" },
    { value: "ישורון יסודי חיפה", label: "ישורון יסודי חיפה" },
    { value: "ישורון יסודי פתח תקווה", label: "ישורון יסודי פתח תקווה" },
    { value: "כרמל צבולון תיכון חיפה", label: "כרמל צבולון תיכון חיפה" },
    { value: "כרמל יסודי חיפה", label: "כרמל יסודי חיפה" },
    { value: "כרמל יסודי ירושלים", label: "כרמל יסודי ירושלים" },
    { value: "כרמל יסודי תל אביב", label: "כרמל יסודי תל אביב" },
    { value: "כרמל יסודי באר שבע", label: "כרמל יסודי באר שבע" },
    { value: "כנרת יסודי טבריה", label: "כנרת יסודי טבריה" },
    { value: "כנרת יסודי צפת", label: "כנרת יסודי צפת" },
    { value: "כנרת יסודי קרית שמונה", label: "כנרת יסודי קרית שמונה" },
    { value: "כנרת יסודי נהריה", label: "כנרת יסודי נהריה" },
    { value: "כנרת יסודי עכו", label: "כנרת יסודי עכו" },
    { value: "לאה גולדברג יסודי חולון", label: "לאה גולדברג יסודי חולון" },
    { value: "לאה גולדברג יסודי תל אביב", label: "לאה גולדברג יסודי תל אביב" },
    { value: "לאה גולדברג יסודי ירושלים", label: "לאה גולדברג יסודי ירושלים" },
    { value: "לאה גולדברג יסודי חיפה", label: "לאה גולדברג יסודי חיפה" },
    { value: "לאה גולדברג יסודי באר שבע", label: "לאה גולדברג יסודי באר שבע" },
    { value: "מקיף א' אשדוד", label: "מקיף א' אשדוד" },
    { value: "מקיף ב' פתח תקווה", label: "מקיף ב' פתח תקווה" },
    { value: "מקיף ג' חיפה", label: "מקיף ג' חיפה" },
    { value: "מקיף ד' באר שבע", label: "מקיף ד' באר שבע" },
    { value: "מקיף ה' ראשון לציון", label: "מקיף ה' ראשון לציון" },
    { value: "מקיף ו' נתניה", label: "מקיף ו' נתניה" },
    { value: "מקיף ז' ירושלים", label: "מקיף ז' ירושלים" },
    { value: "מקיף ח' תל אביב", label: "מקיף ח' תל אביב" },
    { value: "מקיף ט' חולון", label: "מקיף ט' חולון" },
    { value: "מקיף י' בת ים", label: "מקיף י' בת ים" },
    { value: "מקיף יא' אשקלון", label: "מקיף יא' אשקלון" },
    { value: "מקיף יב' רחובות", label: "מקיף יב' רחובות" },
    { value: "מקיף יג' קרית גת", label: "מקיף יג' קרית גת" },
    { value: "מקיף יד' דימונה", label: "מקיף יד' דימונה" },
    { value: "מקיף טו' אילת", label: "מקיף טו' אילת" },
    { value: "מבואות עירון תיכון קרית שמונה", label: "מבואות עירון תיכון קרית שמונה" },
    { value: "משגב יסודי כרמיאל", label: "משגב יסודי כרמיאל" },
    { value: "משגב יסודי חיפה", label: "משגב יסודי חיפה" },
    { value: "משגב יסודי צפת", label: "משגב יסודי צפת" },
    { value: "משגב יסודי נהריה", label: "משגב יסודי נהריה" },
    { value: "משגב יסודי עכו", label: "משגב יסודי עכו" },
    { value: "ניצנים יסודי רמת השרון", label: "ניצנים יסודי רמת השרון" },
    { value: "ניצנים יסודי הרצליה", label: "ניצנים יסודי הרצליה" },
    { value: "ניצנים יסודי כפר סבא", label: "ניצנים יסודי כפר סבא" },
    { value: "ניצנים יסודי רעננה", label: "ניצנים יסודי רעננה" },
    { value: "ניצנים יסודי הוד השרון", label: "ניצנים יסודי הוד השרון" },
    { value: "נוף יסודי נצרת", label: "נוף יסודי נצרת" },
    { value: "נוף יסודי עפולה", label: "נוף יסודי עפולה" },
    { value: "נוף יסודי חיפה", label: "נוף יסודי חיפה" },
    { value: "נוף יסודי טבריה", label: "נוף יסודי טבריה" },
    { value: "נוף יסודי כרמיאל", label: "נוף יסודי כרמיאל" },
    { value: "ספיר יסודי הרצליה", label: "ספיר יסודי הרצליה" },
    { value: "ספיר יסודי תל אביב", label: "ספיר יסודי תל אביב" },
    { value: "ספיר יסודי ירושלים", label: "ספיר יסודי ירושלים" },
    { value: "ספיר יסודי חיפה", label: "ספיר יסודי חיפה" },
    { value: "ספיר יסודי באר שבע", label: "ספיר יסודי באר שבע" },
    { value: "עמית חטיבה ירושלים", label: "עמית חטיבה ירושלים" },
    { value: "עמית חטיבה חיפה", label: "עמית חטיבה חיפה" },
    { value: "עמית חטיבה תל אביב", label: "עמית חטיבה תל אביב" },
    { value: "עמית חטיבה באר שבע", label: "עמית חטיבה באר שבע" },
    { value: "עמית חטיבה אשדוד", label: "עמית חטיבה אשדוד" },
    { value: "פרץ יסודי תל אביב", label: "פרץ יסודי תל אביב" },
    { value: "פרץ יסודי ירושלים", label: "פרץ יסודי ירושלים" },
    { value: "פרץ יסודי חיפה", label: "פרץ יסודי חיפה" },
    { value: "פרץ יסודי באר שבע", label: "פרץ יסודי באר שבע" },
    { value: "פרץ יסודי פתח תקווה", label: "פרץ יסודי פתח תקווה" },
    { value: "צמח יסודי באר שבע", label: "צמח יסודי באר שבע" },
    { value: "צמח יסודי דימונה", label: "צמח יסודי דימונה" },
    { value: "צמח יסודי ערד", label: "צמח יסודי ערד" },
    { value: "צמח יסודי אילת", label: "צמח יסודי אילת" },
    { value: "צמח יסודי אופקים", label: "צמח יסודי אופקים" },
    { value: "רמות יסודי ירושלים", label: "רמות יסודי ירושלים" },
    { value: "רמות יסודי תל אביב", label: "רמות יסודי תל אביב" },
    { value: "רמות יסודי חיפה", label: "רמות יסודי חיפה" },
    { value: "רמות יסודי באר שבע", label: "רמות יסודי באר שבע" },
    { value: "רמות יסודי נתניה", label: "רמות יסודי נתניה" },
    { value: "רמות רמז יסודי חיפה", label: "רמות רמז יסודי חיפה" },
    { value: "רחל יסודי גבעת שמואל", label: "רחל יסודי גבעת שמואל" },
    { value: "רחל יסודי פתח תקווה", label: "רחל יסודי פתח תקווה" },
    { value: "רחל יסודי תל אביב", label: "רחל יסודי תל אביב" },
    { value: "רחל יסודי ירושלים", label: "רחל יסודי ירושלים" },
    { value: "Rachel_Elementary_Haifa", label: "רחל יסודי חיפה" },
    { value: "Shazar_Elementary_Jerusalem", label: "שזר יסודי ירושלים" },
    { value: "Shazar_Elementary_TelAviv", label: "שזר יסודי תל אביב" },
    { value: "Shazar_Elementary_Haifa", label: "שזר יסודי חיפה" },
    { value: "Shazar_Elementary_BeerSheva", label: "שזר יסודי באר שבע" },
    { value: "Shazar_Elementary_Ashdod", label: "שזר יסודי אשדוד" },
    { value: "Shilo_Elementary_Ariel", label: "שילה יסודי אריאל" },
    { value: "Shilo_Elementary_Jerusalem", label: "שילה יסודי ירושלים" },
    { value: "Shilo_Elementary_TelAviv", label: "שילה יסודי תל אביב" },
    { value: "Shilo_Elementary_Haifa", label: "שילה יסודי חיפה" },
    { value: "Shilo_Elementary_BeerSheva", label: "שילה יסודי באר שבע" },
    { value: "Sharett_Elementary_Jerusalem", label: "שרת יסודי ירושלים" },
    { value: "Sharett_Elementary_TelAviv", label: "שרת יסודי תל אביב" },
    { value: "Sharett_Elementary_Haifa", label: "שרת יסודי חיפה" },
    { value: "Sharett_Elementary_BeerSheva", label: "שרת יסודי באר שבע" },
    { value: "Sharett_Elementary_Petah_Tikva", label: "שרת יסודי פתח תקווה" },
    { value: "Sheinkin_Elementary_TelAviv", label: "שינקין יסודי תל אביב" },
    { value: "Sheinkin_Elementary_Jerusalem", label: "שינקין יסודי ירושלים" },
    { value: "Sheinkin_Elementary_Haifa", label: "שינקין יסודי חיפה" },
    { value: "Sheinkin_Elementary_RamatGan", label: "שינקין יסודי רמת גן" },
    { value: "Sheinkin_Elementary_Givatayim", label: "שינקין יסודי גבעתיים" },
    { value: "Tchernichovsky_Elementary_TelAviv", label: "טשרניחובסקי יסודי תל אביב" },
    { value: "Tchernichovsky_Elementary_Jerusalem", label: "טשרניחובסקי יסודי ירושלים" },
    { value: "Tchernichovsky_Elementary_Haifa", label: "טשרניחובסקי יסודי חיפה" },
    { value: "Tchernichovsky_Elementary_BeerSheva", label: "טשרניחובסקי יסודי באר שבע" },
    { value: "Tchernichovsky_Elementary_Netanya", label: "טשרניחובסקי יסודי נתניה" },
    { value: "Tchernichovsky_High_School_Holon", label: "טשרניחובסקי תיכון חולון" },
    { value: "Tchernichovsky_High_School_TelAviv", label: "טשרניחובסקי תיכון תל אביב" },
    { value: "Tchernichovsky_High_School_Jerusalem", label: "טשרניחובסקי תיכון ירושלים" },
    { value: "Tchernichovsky_High_School_Haifa", label: "טשרניחובסקי תיכון חיפה" },
    { value: "Tchernichovsky_High_School_BeerSheva", label: "טשרניחובסקי תיכון באר שבע" },
    { value: "Tamar_Elementary_Dimona", label: "תמר יסודי דימונה" },
    { value: "Tamar_Elementary_BeerSheva", label: "תמר יסודי באר שבע" },
    { value: "Tamar_Elementary_Arad", label: "תמר יסודי ערד" },
    { value: "Tamar_Elementary_Eilat", label: "תמר יסודי אילת" },
    { value: "Tamar_Elementary_Ofakim", label: "תמר יסודי אופקים" },
    { value: "Tali_Elementary_Jerusalem", label: "תלי יסודי ירושלים" },
    { value: "Tali_Elementary_TelAviv", label: "תלי יסודי תל אביב" },
    { value: "Tali_Elementary_Haifa", label: "תלי יסודי חיפה" },
    { value: "Tali_Elementary_BeerSheva", label: "תלי יסודי באר שבע" },
    { value: "Tali_Elementary_Netanya", label: "תלי יסודי נתניה" },
    { value: "Taglit_Elementary_Eilat", label: "תגלית יסודי אילת" },
    { value: "Taglit_Elementary_BeerSheva", label: "תגלית יסודי באר שבע" },
    { value: "Taglit_Elementary_Dimona", label: "תגלית יסודי דימונה" },
    { value: "Taglit_Elementary_Arad", label: "תגלית יסודי ערד" },
    { value: "Taglit_Elementary_Ofakim", label: "תגלית יסודי אופקים" },
    { value: "Rogozin_Elementary_TelAviv", label: "רוגוזין יסודי תל אביב" },
    { value: "Rogozin_Elementary_Jerusalem", label: "רוגוזין יסודי ירושלים" },
    { value: "Rogozin_Elementary_Haifa", label: "רוגוזין יסודי חיפה" },
    { value: "Rogozin_Elementary_BeerSheva", label: "רוגוזין יסודי באר שבע" },
    { value: "Rogozin_Elementary_Petah_Tikva", label: "רוגוזין יסודי פתח תקווה" },
    { value: "Nordau_Elementary_TelAviv", label: "נורדאו יסודי תל אביב" },
    { value: "Nordau_Elementary_Jerusalem", label: "נורדאו יסודי ירושלים" },
    { value: "Nordau_Elementary_Haifa", label: "נורדאו יסודי חיפה" },
    { value: "Nordau_Elementary_BeerSheva", label: "נורדאו יסודי באר שבע" },
    { value: "Nordau_Elementary_Netanya", label: "נורדאו יסודי נתניה" },
    { value: "Ahad_Haam_Elementary_TelAviv", label: "אחד העם יסודי תל אביב" },
    { value: "Ahad_Haam_Elementary_Jerusalem", label: "אחד העם יסודי ירושלים" },
    { value: "Ahad_Haam_Elementary_Haifa", label: "אחד העם יסודי חיפה" },
    { value: "Ahad_Haam_Elementary_BeerSheva", label: "אחד העם יסודי באר שבע" },
    { value: "Ahad_Haam_Elementary_RamatGan", label: "אחד העם יסודי רמת גן" },
    { value: "Nes_Ziona_Elementary_Nes_Ziona", label: "נס ציונה יסודי נס ציונה" },
    { value: "Nes_Ziona_Elementary_Rehovot", label: "נס ציונה יסודי רחובות" },
    { value: "Nes_Ziona_Elementary_Yavne", label: "נס ציונה יסודי יבנה" },
    { value: "Nes_Ziona_Elementary_Ashdod", label: "נס ציונה יסודי אשדוד" },
    { value: "Nes_Ziona_Elementary_Ashkelon", label: "נס ציונה יסודי אשקלון" },
    { value: "Rambam_Elementary_Rehovot", label: "רמב\"ם יסודי רחובות" },
    { value: "Rambam_Elementary_Jerusalem", label: "רמב\"ם יסודי ירושלים" },
    { value: "Rambam_Elementary_TelAviv", label: "רמב\"ם יסודי תל אביב" },
    { value: "Rambam_Elementary_Haifa", label: "רמב\"ם יסודי חיפה" },
    { value: "Rambam_Elementary_BeerSheva", label: "רמב\"ם יסודי באר שבע" },
    { value: "Einstein_Elementary_Rehovot", label: "איינשטיין יסודי רחובות" },
    { value: "Einstein_Elementary_Jerusalem", label: "איינשטיין יסודי ירושלים" },
    { value: "Einstein_Elementary_TelAviv", label: "איינשטיין יסודי תל אביב" },
    { value: "Einstein_Elementary_Haifa", label: "איינשטיין יסודי חיפה" },
    { value: "Einstein_Elementary_BeerSheva", label: "איינשטיין יסודי באר שבע" },
    { value: "Weizmann_Elementary_Rehovot", label: "ויצמן יסודי רחובות" },
    { value: "Weizmann_Elementary_Jerusalem", label: "ויצמן יסודי ירושלים" },
    { value: "Weizmann_Elementary_TelAviv", label: "ויצמן יסודי תל אביב" },
    { value: "Weizmann_Elementary_Haifa", label: "ויצמן יסודי חיפה" },
    { value: "Weizmann_Elementary_BeerSheva", label: "ויצמן יסודי באר שבע" },
    { value: "Kiryat_Eliezer_Elementary_Haifa", label: "קרית אליעזר יסודי חיפה" },
    { value: "Kiryat_Yam_Elementary_Kiryat_Yam", label: "קרית ים יסודי קרית ים" },
    { value: "Kiryat_Motzkin_Elementary_Kiryat_Motzkin", label: "קרית מוצקין יסודי קרית מוצקין" },
    { value: "Nesher_Elementary_Nesher", label: "נשר יסודי נשר" },
    { value: "Kiryat_Ata_Elementary_Kiryat_Ata", label: "קרית אתא יסודי קרית אתא" },
    { value: "Nahariya_Elementary_Nahariya", label: "נהריה יסודי נהריה" },
    { value: "Akko_Elementary_Acre", label: "עכו יסודי עכו" },
    { value: "Maalot_Elementary_Maalot_Tarshiha", label: "מעלות יסודי מעלות-תרשיחא" },
    { value: "Kiryat_Shmona_Elementary_Kiryat_Shmona", label: "קרית שמונה יסודי קרית שמונה" },
    { value: "Safed_Elementary_Safed", label: "צפת יסודי צפת" },
    { value: "Tiberias_Elementary_Tiberias", label: "טבריה יסודי טבריה" },
    { value: "Nazareth_Elementary_Nazareth", label: "נצרת יסודי נצרת" },
    { value: "Afula_Elementary_Afula", label: "עפולה יסודי עפולה" },
    { value: "Migdal_HaEmek_Elementary_Migdal_HaEmek", label: "מגדל העמק יסודי מגדל העמק" },
    { value: "Yokneam_Elementary_Yokneam", label: "יקנעם יסודי יקנעם" },
    { value: "Carmiel_Elementary_Carmiel", label: "כרמיאל יסודי כרמיאל" },
    { value: "Nof_HaGalil_Elementary_Nof_HaGalil", label: "נוף הגליל יסודי נוף הגליל" },
    { value: "Sakhnin_Elementary_Sakhnin", label: "סח'נין יסודי סח'נין" },
    { value: "Tamra_Elementary_Tamra", label: "תמרה יסודי תמרה" },
    { value: "Tayibe_Elementary_Tayibe", label: "טייבה יסודי טייבה" },
    { value: "Tira_Elementary_Tira", label: "טירה יסודי טירה" },
    { value: "Kafr_Qasim_Elementary_Kafr_Qasim", label: "כפר קאסם יסודי כפר קאסם" },
    { value: "Qalansawe_Elementary_Qalansawe", label: "קלנסווה יסודי קלנסווה" },
    { value: "Baqa_al_Gharbiyye_Elementary_Baqa_al_Gharbiyye", label: "באקה אל-גרביה יסודי באקה אל-גרביה" },
    { value: "Umm_al_Fahm_Elementary_Umm_al_Fahm", label: "אום אל-פחם יסודי אום אל-פחם" },
    { value: "BeerSheva_Elementary_BeerSheva", label: "באר שבע יסודי באר שבע" },
    { value: "Arad_Elementary_Arad", label: "ערד יסודי ערד" },
    { value: "Dimona_Elementary_Dimona", label: "דימונה יסודי דימונה" },
    { value: "Ofakim_Elementary_Ofakim", label: "אופקים יסודי אופקים" },
    { value: "Netivot_Elementary_Netivot", label: "נתיבות יסודי נתיבות" },
    { value: "Sderot_Elementary_Sderot", label: "שדרות יסודי שדרות" },
    { value: "Eilat_Elementary_Eilat", label: "אילת יסודי אילת" },
    { value: "Mitzpe_Ramon_Elementary_Mitzpe_Ramon", label: "מצפה רמון יסודי מצפה רמון" },
    { value: "Yeroham_Elementary_Yeroham", label: "ירוחם יסודי ירוחם" },
    { value: "Kiryat_Malakhi_Elementary_Kiryat_Malakhi", label: "קרית מלאכי יסודי קרית מלאכי" },
    { value: "Kiryat_Gat_Elementary_Kiryat_Gat", label: "קרית גת יסודי קרית גת" },
    { value: "Lod_Elementary_Lod", label: "לוד יסודי לוד" },
    { value: "Ramla_Elementary_Ramla", label: "רמלה יסודי רמלה" },
    { value: "Bet_Shemesh_Elementary_Bet_Shemesh", label: "בית שמש יסודי בית שמש" },
    { value: "Maale_Adumim_Elementary_Maale_Adumim", label: "מעלה אדומים יסודי מעלה אדומים" },
    { value: "Beitar_Illit_Elementary_Beitar_Illit", label: "ביתר עילית יסודי ביתר עילית" },
    { value: "Modiin_Illit_Elementary_Modiin_Illit", label: "מודיעין עילית יסודי מודיעין עילית" },
    { value: "Or_Yehuda_Elementary_Or_Yehuda", label: "אור יהודה יסודי אור יהודה" },
    { value: "Yehud_Elementary_Yehud", label: "יהוד יסודי יהוד" },
    { value: "Kiryat_Ono_Elementary_Kiryat_Ono", label: "קרית אונו יסודי קרית אונו" },
    { value: "Even_Yehuda_Elementary_Even_Yehuda", label: "אבן יהודה יסודי אבן יהודה" },
    { value: "Or_Akiva_Elementary_Or_Akiva", label: "אור עקיבא יסודי אור עקיבא" },
    { value: "Zikhron_Yaakov_Elementary_Zikhron_Yaakov", label: "זכרון יעקב יסודי זכרון יעקב" },
    { value: "Shoham_Elementary_Shoham", label: "שוהם יסודי שוהם" },
    { value: "Rosh_HaAyin_Elementary_Rosh_HaAyin", label: "ראש העין יסודי ראש העין" },
    { value: "Elad_Elementary_Elad", label: "אלעד יסודי אלעד" },
    { value: "Beit_Shean_Elementary_Beit_Shean", label: "בית שאן יסודי בית שאן" },
    { value: "Qatzrin_Elementary_Qatzrin", label: "קצרין יסודי קצרין" }
];