import {
    DAILY_TEACHER_COL_DATA_CHANGED,
    DAILY_SCHEDULE_DATA_CHANGED,
    ENTITIES_DATA_CHANGED,
    DAILY_PUBLISH_DATA_CHANGED,
    MATERIAL_CHANGED
} from "../constant/sync";

export type SyncChannel =
    | typeof DAILY_TEACHER_COL_DATA_CHANGED
    | typeof DAILY_SCHEDULE_DATA_CHANGED
    | typeof ENTITIES_DATA_CHANGED
    | typeof DAILY_PUBLISH_DATA_CHANGED
    | typeof MATERIAL_CHANGED;
